### PR TITLE
adding rst tables comparison

### PR DESCRIPTION
**Pull request by choldgraf**
This adds a few tables in the syntax page to compare one vs the other...what do folks think? Good way to compare?

### CODE REVIEW

**Comment by choldgraf** [comment]
Here's how one of them looks - I'm not a huge fan of the CSS but I do think the layout is useful: https://49-240151150-gh.circle-artifacts.com/0/html/syntax.html#extra-markdown-syntax

**Comment by chrisjsewell** [comment]
Quick question first, how to you find out the links for CircleCI build artifacts?

**Comment by chrisjsewell** [comment]
Looks good to me though 👍

**Comment by choldgraf** [comment]
Mostly, click on the circle link, go to "Artifacts", then click `index.html` from the dropdown list. You may need CircleCI permissions for this though - let me know if I need to add you or something.

There are also a few bots that will auto-post a link to the documentation alongside your CircleCI link...I'll set that up at some point, just havne't gotten around to it. E.g.:

https://github.com/larsoner/circleci-artifacts-redirector-action

**Comment by chrisjsewell** [comment]
I can't see any "Artifacts" section?

image

**Comment by choldgraf** [comment]
Hmmm - it looks like you may not be logged in with your CircleCI account. Can you make sure it is connected w/ your GitHub account, and that you're logged in, and try again?

**Comment by chrisjsewell** [comment]
Sorted ta, for some reason I had to log out and log back in, and now it is showing up

**Pull request merged**
