### PR TITLE
adding rtd docs

### PR DESCRIPTION
**Pull request by choldgraf**

### CODE REVIEW

**Comment by chrisjsewell** [comment]
Do you know how to use pre-commit? Let me know if you need any help.

**Comment by choldgraf** [comment]
yep - waiting for it to install now :-)

**Comment by choldgraf** [comment]
woo - got it working, latest push should fix the flakiness

**Comment by chrisjsewell** [comment]
We might also want to add the document build to the Travis CI. For example as I do here: https://github.com/chrisjsewell/ase-notebook/blob/master/.travis.yml

**Comment by choldgraf** [comment]
@chrisjsewell agree - usually I do this in a CircleCI job because then it's quite easy to build a preview that you can click on before merging...you +1 on me adding a PR that does this? (probably later on)

**Comment by chrisjsewell** [comment]
Sounds good to me

**Comment by choldgraf** [comment]
hmmm weird - I've got flake8 and black both passing locally...I'm not sure why travis isn't passing

**Comment by chrisjsewell** [comment]
Have you actually installed/run pre-commit though, all of the errors are from trailing whitespace which are 'fixed' by the `trailing-whitespace` pre-commit hook

**Comment by choldgraf** [comment]
Yep, I've got this in the outputs from my commit:

```
Trim Trailing Whitespace.................................................Passed
```

Weird...

**Comment by chrisjsewell** [comment]
Strange? Are there still trailing white spaces in your local files, as shown in the travis diff: https://travis-ci.org/ExecutableBookProject/myst_parser/jobs/649830302#L352

**Comment by choldgraf** [comment]
Not at the computer now, but I just had a thought - I bet it is CRLF vs LF carriage returns. Will check when I am back at home

**Comment by choldgraf** [comment]
sweet - tests passed, gonna merge and see if RTD works too

**Pull request merged**
